# Generated by Django 5.2.3 on 2025-11-05 08:11

import CORE.models
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('shift', models.CharField(blank=True, choices=[('MORNING', 'Morning (9AM-5PM)'), ('EVENING', 'Evening (1PM-9PM)'), ('NIGHT', 'Night (9PM-5AM)'), ('FLEX', 'Flexible')], default='MORNING', max_length=10, null=True)),
                ('pay_grade', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='role', chained_model_field='role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.master_pay_grade_level')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.master_role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(help_text="Customer's primary contact number", max_length=128, region='IN')),
                ('address', models.TextField(blank=True, help_text="Customer's full mailing address", null=True)),
                ('description', models.TextField(blank=True, help_text="Internal notes about the customer (e.g., 'V.I.P.', 'Prefers afternoon calls')", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('employee', models.OneToOneField(limit_choices_to={'role__name': 'Accountant'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CORE.employee')),
                ('education', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('employee', models.OneToOneField(limit_choices_to={'role__name': 'Advisor'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CORE.employee')),
                ('education_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('employee', models.OneToOneField(limit_choices_to={'role__name': 'Cashier'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CORE.employee')),
                ('counter_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('employee', models.OneToOneField(limit_choices_to={'role__name': 'Mechanic'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CORE.employee')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('expertise_area', models.ForeignKey(limit_choices_to={'role__name': 'Mechanic'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_expertise_area')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('description_of_service', models.TextField()),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='CORE.customer')),
            ],
            options={
                'verbose_name': 'Service Record',
                'verbose_name_plural': 'Service Records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='Masters.master_spare_part_type')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='Masters.master_vehicle_model')),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Spare Parts',
                'unique_together': {('vehicle_model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the part at the time of service.', max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.service')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.sparepart')),
            ],
            options={
                'verbose_name': 'Part Used in Service',
                'verbose_name_plural': 'Parts Used in Service',
                'unique_together': {('service', 'part')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='parts',
            field=models.ManyToManyField(related_name='services_used_in', through='CORE.ServicePart', to='CORE.sparepart'),
        ),
        migrations.CreateModel(
            name='InventoryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('quantity_received', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost for this batch', max_digits=10)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='CORE.sparepart')),
            ],
            options={
                'verbose_name': 'Inventory Invoice',
                'verbose_name_plural': 'Inventory Invoices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=17, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=CORE.models.get_current_year, help_text='Year of manufacture')),
                ('description', models.TextField(blank=True, help_text='e.g., Color, dents, or other notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='CORE.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='Masters.master_vehicle_model')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='CORE.vehicle'),
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Final amount for this service, calculated on creation.', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='CORE.service')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_generated', to='CORE.cashier')),
            ],
            options={
                'verbose_name': 'Service Invoice',
                'verbose_name_plural': 'Service Invoices',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='CORE.mechanic'),
        ),
    ]
