# Generated by Django 5.2.7 on 2025-10-22 16:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(help_text="Customer's primary contact number", max_length=128, region='IN')),
                ('address', models.TextField(blank=True, help_text="Customer's full mailing address", null=True)),
                ('description', models.TextField(blank=True, help_text="Internal notes about the customer (e.g., 'V.I.P.', 'Prefers afternoon calls')", null=True)),
            ],
        ),
    ]
