# Generated by Django 5.2.3 on 2025-10-28 16:40

import Customer.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(help_text="Customer's primary contact number", max_length=128, region='IN')),
                ('address', models.TextField(blank=True, help_text="Customer's full mailing address", null=True)),
                ('description', models.TextField(blank=True, help_text="Internal notes about the customer (e.g., 'V.I.P.', 'Prefers afternoon calls')", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=17, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=Customer.models.get_current_year, help_text='Year of manufacture')),
                ('description', models.TextField(blank=True, help_text='e.g., Color, dents, or other notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Customer.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='Masters.master_vehicle_model')),
            ],
        ),
    ]
