# Generated by Django 5.2.7 on 2025-10-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MASTER_expertise_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MASTER_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MASTER_vehicle_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MASTER - Vehicle Brands',
            },
        ),
        migrations.CreateModel(
            name='MASTER_vehicle_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('licence_type', models.CharField(blank=True, max_length=20)),
                ('wheels', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'MASTER - Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='MASTER_pay_grade_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.master_role')),
            ],
            options={
                'unique_together': {('role', 'level')},
            },
        ),
        migrations.CreateModel(
            name='MASTER_vehicle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(blank=True, max_length=50)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Masters.master_vehicle_brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='Masters.master_vehicle_category')),
            ],
            options={
                'verbose_name_plural': 'MASTER - Vehicle Models',
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
