# Generated by Django 5.2.7 on 2025-10-22 19:45

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.master_role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Employee.employee')),
                ('education', models.TextField(blank=True, null=True)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (9AM-5PM)'), ('EVENING', 'Evening (1PM-9PM)'), ('NIGHT', 'Night (9PM-5AM)'), ('FLEX', 'Flexible')], default='MORNING', max_length=10)),
                ('pay_grade', models.ForeignKey(limit_choices_to={'role__name': 'Accountant'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level')),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Employee.employee')),
                ('education_desc', models.TextField(blank=True, null=True)),
                ('pay_grade', models.ForeignKey(limit_choices_to={'role__name': 'Advisor'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level')),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Employee.employee')),
                ('counter_number', models.CharField(max_length=10)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (9AM-5PM)'), ('EVENING', 'Evening (1PM-9PM)'), ('NIGHT', 'Night (9PM-5AM)'), ('FLEX', 'Flexible')], default='MORNING', max_length=10)),
                ('pay_grade', models.ForeignKey(limit_choices_to={'role__name': 'Cashier'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Employee.employee')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (9AM-5PM)'), ('EVENING', 'Evening (1PM-9PM)'), ('NIGHT', 'Night (9PM-5AM)'), ('FLEX', 'Flexible')], default='MORNING', max_length=10)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('expertise_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.master_expertise_area')),
                ('pay_grade', models.ForeignKey(limit_choices_to={'role__name': 'Mechanic'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level')),
            ],
        ),
    ]
