# Generated by Django 5.2.7 on 2025-10-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='expertise_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.master_expertise_area'),
        ),
        migrations.AlterUniqueTogether(
            name='master_pay_grade_level',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='master_pay_grade_level',
            name='role',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='pay_grade',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Advisor'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='pay_grade',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Cashier'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='pay_grade',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Mechanic'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='pay_grade',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Accountant'}, on_delete=django.db.models.deletion.PROTECT, to='Masters.master_pay_grade_level'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.master_role'),
        ),
        migrations.DeleteModel(
            name='MASTER_expertise_area',
        ),
        migrations.DeleteModel(
            name='MASTER_pay_grade_level',
        ),
        migrations.DeleteModel(
            name='MASTER_role',
        ),
    ]
