# Generated by Django 5.2.7 on 2025-10-22 19:45

import Vehicle.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=17, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=Vehicle.models.get_current_year, help_text='Year of manufacture')),
                ('description', models.TextField(blank=True, help_text='e.g., Color, dents, or other notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Customer.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='Masters.master_vehicle_model')),
            ],
        ),
    ]
