# Generated by Django 5.2.3 on 2025-10-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Employee', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('description_of_service', models.TextField()),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='Customer.customer')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='Employee.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='Customer.vehicle')),
            ],
            options={
                'verbose_name': 'Service Record',
                'verbose_name_plural': 'Service Records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Final amount for this service, calculated on creation.', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_generated', to='Employee.cashier')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='Service.service')),
            ],
            options={
                'verbose_name': 'Service Invoice',
                'verbose_name_plural': 'Service Invoices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the part at the time of service.', max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.sparepart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
            ],
            options={
                'verbose_name': 'Part Used in Service',
                'verbose_name_plural': 'Parts Used in Service',
                'unique_together': {('service', 'part')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='parts',
            field=models.ManyToManyField(related_name='services_used_in', through='Service.ServicePart', to='Inventory.sparepart'),
        ),
    ]
